"""Uprate clean FRS microdata between years (either direction).

Python port of the Rust `Dataset::uprate_to_dir` (src/data/mod.rs): applies
year-on-year growth indices to monetary columns and the population index to
weights. Rates come from the `growth_factors` block of each parameter YAML
(generated by data/gen_growth_factors.py from the OBR EFO workbook and MHCLG
council tax tables), with a hardcoded fallback table for years/indices missing
from the YAMLs.

Used for pooling adjacent FRS years onto a common price level, and for shifting
the fixed EFRS panel to each target year (de-uprating for years before the
base). Operates on the clean persons/households CSV columns; benunits carry no
monetary fields and are passed through unchanged.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
PARAMS_DIR = REPO_ROOT / "parameters"

# ── Fallback hardcoded rates (used when a YAML is unavailable or for indices
# not carried in growth_factors). Mirrors src/data/mod.rs::yoy_rates. ──
_YOY: dict[str, list[tuple[int, float]]] = {
    "earnings": [
        (2022, 0.0614),
        (2023, 0.0622),
        (2024, 0.0493),
        (2025, 0.0517),
        (2026, 0.0333),
        (2027, 0.0225),
        (2028, 0.0210),
        (2029, 0.0221),
        (2030, 0.0232),
    ],
    "cpi": [
        (2022, 0.0907),
        (2023, 0.0730),
        (2024, 0.0253),
        (2025, 0.0345),
        (2026, 0.0248),
        (2027, 0.0202),
        (2028, 0.0204),
        (2029, 0.0204),
        (2030, 0.0200),
    ],
    "gdp_pc": [
        (2022, 0.1019),
        (2023, 0.0532),
        (2024, 0.0372),
        (2025, 0.0418),
        (2026, 0.0327),
        (2027, 0.0326),
        (2028, 0.0302),
        (2029, 0.0294),
        (2030, 0.0306),
    ],
    "mixed_pc": [
        (2022, 0.0296),
        (2023, -0.0060),
        (2024, 0.0273),
        (2025, 0.0024),
        (2026, 0.0362),
        (2027, 0.0374),
        (2028, 0.0351),
        (2029, 0.0358),
        (2030, 0.0364),
    ],
    "rent": [
        (2022, 0.0347),
        (2023, 0.0575),
        (2024, 0.0716),
        (2025, 0.0546),
        (2026, 0.0334),
        (2027, 0.0311),
        (2028, 0.0243),
        (2029, 0.0234),
        (2030, 0.0254),
    ],
    "council_tax": [
        (2023, 0.051),
        (2024, 0.051),
        (2025, 0.0781),
        (2026, 0.0530),
        (2027, 0.0579),
        (2028, 0.0565),
        (2029, 0.0547),
        (2030, 0.0542),
    ],
    # Social rent settlement (England): -1% a year April 2016-2019 (Welfare
    # Reform and Work Act 2016 rent reduction), then September-CPI + 1ppt
    # (MHCLG policy statement on rents for social housing), with the 7%
    # ceiling in 2023/24. Sept CPI: ONS D7G7 (2019: 1.7, 2020: 0.5, 2021: 3.1,
    # 2022: 10.1 -> capped, 2023: 6.7, 2024: 1.7, 2025: 3.8). Years beyond the
    # table fall back to fiscal-year CPI + 1ppt in _rate_for.
    "social_rent": [
        (2016, -0.01),
        (2017, -0.01),
        (2018, -0.01),
        (2019, -0.01),
        (2020, 0.027),
        (2021, 0.015),
        (2022, 0.041),
        (2023, 0.070),
        (2024, 0.077),
        (2025, 0.027),
        (2026, 0.048),
    ],
    "population": [
        (2022, 0.0093),
        (2023, 0.0131),
        (2024, 0.0107),
        (2025, 0.0072),
        (2026, 0.0038),
        (2027, 0.0037),
        (2028, 0.0040),
        (2029, 0.0044),
        (2030, 0.0045),
    ],
    "interest": [
        (2022, 1.210),
        (2023, 0.987),
        (2024, 0.142),
        (2025, 0.0519),
        (2026, 0.0565),
        (2027, 0.0474),
        (2028, 0.0364),
        (2029, 0.0302),
        (2030, 0.0292),
    ],
}

_DEFAULT_RATE: dict[str, float] = {
    "earnings": 0.0383,
    "cpi": 0.0200,
    "gdp_pc": 0.0306,
    "mixed_pc": 0.0364,
    "rent": 0.0254,
    "council_tax": 0.0542,
    "population": 0.0045,
    "interest": 0.0292,
}


@lru_cache(maxsize=32)
def _yaml_growth_factors(year: int) -> dict[str, float]:
    """Read growth_factors from the parameter YAML for the transition into `year`.

    The YAML for fiscal year Y/Y+1 carries the OBR rates for the transition
    *into* year Y, so year=2026 reads 2026_27.yaml. This matches the fallback
    `_YOY` table, which keys rates on the entered fiscal year.
    Returns an empty dict when the file is missing or has no growth_factors block.
    """
    fname = f"{year}_{(year + 1) % 100:02d}.yaml"
    path = PARAMS_DIR / fname
    if not path.exists():
        return {}
    with path.open() as f:
        data = yaml.safe_load(f)
    return data.get("growth_factors") or {}


# Index name → growth_factors YAML key.
_YAML_KEY: dict[str, str] = {
    "earnings": "earnings_growth",
    "cpi": "cpi_rate",
    "gdp_pc": "gdp_pc_growth",
    "mixed_pc": "mixed_income_pc_growth",
    "interest": "savings_interest_growth",
    "rent": "rent_growth",
    "mortgage_interest": "mortgage_interest_growth",
    "population": "population_growth",
    "council_tax": "council_tax_growth",
}


def _rate_for(year: int, index: str) -> float:
    """Year-on-year rate for `index` entering fiscal year `year`.

    Prefers the YAML growth_factors value; falls back to the hardcoded table
    (then the default rate) when the YAML or key is unavailable.
    """
    if index == "social_rent":
        rates = dict(_YOY["social_rent"])
        if year in rates:
            return rates[year]
        # Beyond the settlement table: CPI + 1ppt (forecast approximation,
        # fiscal-year CPI standing in for September CPI).
        return _rate_for(year, "cpi") + 0.01
    gf = _yaml_growth_factors(year)
    rate = gf.get(_YAML_KEY[index], 0.0)
    if rate != 0.0:
        return rate
    if index not in _YOY:
        raise KeyError(
            f"no growth_factors YAML value for index {index!r} entering "
            f"{year} and no fallback table"
        )
    rates = dict(_YOY[index])
    return rates.get(year, _DEFAULT_RATE[index])


def cumulative_factor(base_year: int, target_year: int, index: str) -> float:
    """Cumulative growth factor from base_year to target_year for an index.

    Reads rates from parameter YAML growth_factors blocks; falls back to the
    hardcoded table for missing years/indices.
    """
    if target_year == base_year:
        return 1.0
    factor = 1.0
    if target_year > base_year:
        for y in range(base_year + 1, target_year + 1):
            factor *= 1.0 + _rate_for(y, index)
    else:
        for y in range(target_year + 1, base_year + 1):
            factor /= 1.0 + _rate_for(y, index)
    return factor


# ── Column → index assignments (clean-CSV column names). Mirrors the field
# assignments in uprate_to; struct fields are mapped to their CSV column names
# (e.g. pension_income → private_pension_income). Columns not listed (counts,
# components, capital_gains, ids, ages) are left unchanged, matching Rust. ──
_PERSON_COLS: dict[str, list[str]] = {
    "earnings": [
        "employment_income",
        "employee_pension_contributions",
        "personal_pension_contributions",
        # Matches Rust: private pension income is wage-linked, and both the
        # gdp_pc and mixed_pc indices over-grew these relative to the OBR
        # baseline (see src/data/mod.rs apply_uprating).
        "private_pension_income",
        "self_employment_income",
    ],
    "gdp_pc": [
        "dividend_income",
        "property_income",
        "maintenance_income",
        "miscellaneous_income",
        "other_income",
    ],
    "interest": ["savings_interest"],
    "cpi": [
        "state_pension",
        "child_benefit",
        "housing_benefit",
        "income_support",
        "pension_credit",
        "child_tax_credit",
        "working_tax_credit",
        "universal_credit",
        "dla_care",
        "dla_mobility",
        "pip_daily_living",
        "pip_mobility",
        "carers_allowance",
        "attendance_allowance",
        "esa_income",
        "esa_contributory",
        "jsa_income",
        "jsa_contributory",
        "other_benefits",
        "adp_daily_living",
        "adp_mobility",
        "cdp_care",
        "cdp_mobility",
        "childcare_expenses",
    ],
}

_HOUSEHOLD_COLS: dict[str, list[str]] = {
    "earnings": [
        "owned_land",
        "property_wealth",
        "corporate_wealth",
        "gross_financial_wealth",
        "net_financial_wealth",
        "main_residence_value",
        "other_residential_property_value",
        "non_residential_property_value",
        "savings",
    ],
    # rent_annual is handled per-tenure in uprate_households: social renters
    # (tenure_type 2 council, 3 housing association) follow the social rent
    # settlement, private renters (4) the market rent index.
    "council_tax": ["council_tax_annual"],
    "cpi": [
        "food_consumption",
        "alcohol_consumption",
        "tobacco_consumption",
        "clothing_consumption",
        "housing_water_electricity_consumption",
        "furnishings_consumption",
        "health_consumption",
        "transport_consumption",
        "communication_consumption",
        "recreation_consumption",
        "education_consumption",
        "restaurants_consumption",
        "miscellaneous_consumption",
        "petrol_spending",
        "diesel_spending",
        "domestic_energy_consumption",
        "electricity_consumption",
        "gas_consumption",
    ],
}


# ── National minimum wage floor ──────────────────────────────────────────────
# Hourly NMW/NLW rates by fiscal year as (min_age, rate) bands, highest band
# first. Source: gov.uk NMW rates pages and the LPC rates history workbook
# (20 years of the National Minimum Wage). 2016/17 uses the October 2016
# youth rates. Apprentice rates are not modelled (apprentices are not
# identifiable in the microdata). Years beyond the table grow the April 2026
# rates with average earnings (RF LSO convention: the bite is maintained).
_NMW_BANDS: dict[int, list[tuple[int, float]]] = {
    2016: [(25, 7.20), (21, 6.95), (18, 5.55), (16, 4.00)],
    2017: [(25, 7.50), (21, 7.05), (18, 5.60), (16, 4.05)],
    2018: [(25, 7.83), (21, 7.38), (18, 5.90), (16, 4.20)],
    2019: [(25, 8.21), (21, 7.70), (18, 6.15), (16, 4.35)],
    2020: [(25, 8.72), (21, 8.20), (18, 6.45), (16, 4.55)],
    2021: [(23, 8.91), (21, 8.36), (18, 6.56), (16, 4.62)],
    2022: [(23, 9.50), (21, 9.18), (18, 6.83), (16, 4.81)],
    2023: [(23, 10.42), (21, 10.18), (18, 7.49), (16, 5.28)],
    2024: [(21, 11.44), (18, 8.60), (16, 6.40)],
    2025: [(21, 12.21), (18, 10.00), (16, 7.55)],
    2026: [(21, 12.71), (18, 10.85), (16, 8.00)],
}


def nmw_bands(year: int) -> list[tuple[int, float]]:
    if year <= 2016:
        return _NMW_BANDS[2016]
    if year in _NMW_BANDS:
        return _NMW_BANDS[year]
    last = max(_NMW_BANDS)
    factor = cumulative_factor(last, year, "earnings")
    return [(age, rate * factor) for age, rate in _NMW_BANDS[last]]


def _nmw_hourly(age: np.ndarray, year: int) -> np.ndarray:
    floor = np.zeros(len(age))
    for min_age, rate in sorted(nmw_bands(year), key=lambda b: b[0]):
        floor = np.where(age >= min_age, rate, floor)
    return floor


def apply_nmw_floor(
    shifted: pd.DataFrame,
    base: pd.DataFrame,
    base_year: int,
    year: int,
) -> pd.DataFrame:
    """Impose the NMW/NLW wage path on the uniformly-uprated panel.

    Uniform earnings uprating misses the NLW rising much faster than average
    earnings since 2016 (and matching earnings growth in the forecast).
    Workers at or below the age-appropriate floor in the base year — largely
    FRS hours/earnings measurement noise — track the NMW index for their age
    band, preserving their measured gap rather than "correcting" it. Workers
    above the base-year floor keep the earnings index but are floored at the
    target year's NMW. No spillovers above the floor are modelled.
    """
    out = shifted.copy()
    hours = base["hours_worked_annual"].to_numpy(dtype=float)
    base_earn = base["employment_income"].to_numpy(dtype=float)
    age = base["age"].to_numpy(dtype=float)
    worked = (hours > 0) & (base_earn > 0)

    nmw_base = _nmw_hourly(age, base_year)
    nmw_year = _nmw_hourly(age, year)
    with np.errstate(divide="ignore", invalid="ignore"):
        hourly_base = np.where(worked, base_earn / hours, np.inf)

    shifted_earn = out["employment_income"].to_numpy(dtype=float)
    at_floor = worked & (hourly_base <= nmw_base)
    with np.errstate(divide="ignore", invalid="ignore"):
        nmw_index = np.where(nmw_base > 0, nmw_year / nmw_base, 1.0)
    floored = np.where(
        at_floor,
        base_earn * nmw_index,
        np.maximum(shifted_earn, np.where(worked, nmw_year * hours, 0.0)),
    )
    out["employment_income"] = np.where(worked, floored, shifted_earn)
    return out


def _apply(
    df: pd.DataFrame, col_map: dict[str, list[str]], base_year: int, target_year: int
) -> pd.DataFrame:
    out = df.copy()
    for index, cols in col_map.items():
        f = cumulative_factor(base_year, target_year, index)
        for c in cols:
            if c in out.columns:
                out[c] = out[c].to_numpy(dtype=float) * f
    return out


def uprate_persons(
    persons: pd.DataFrame, base_year: int, target_year: int
) -> pd.DataFrame:
    if target_year == base_year:
        return persons.copy()
    return _apply(persons, _PERSON_COLS, base_year, target_year)


def uprate_households(
    households: pd.DataFrame, base_year: int, target_year: int
) -> pd.DataFrame:
    """Uprate monetary household columns and scale weights by the population index."""
    if target_year == base_year:
        return households.copy()
    out = _apply(households, _HOUSEHOLD_COLS, base_year, target_year)
    if "rent_annual" in out.columns:
        private_f = cumulative_factor(base_year, target_year, "rent")
        social_f = cumulative_factor(base_year, target_year, "social_rent")
        tenure = out.get("tenure_type")
        if tenure is not None:
            social = tenure.astype(int).isin([2, 3]).to_numpy()
            rent = out["rent_annual"].to_numpy(dtype=float)
            out["rent_annual"] = rent * np.where(social, social_f, private_f)
        else:
            out["rent_annual"] = out["rent_annual"].to_numpy(dtype=float) * private_f
    if "mortgage_interest_annual" in out.columns:
        f = cumulative_factor(base_year, target_year, "mortgage_interest")
        out["mortgage_interest_annual"] = (
            out["mortgage_interest_annual"].to_numpy(dtype=float) * f
        )
    if "weight" in out.columns:
        pop = cumulative_factor(base_year, target_year, "population")
        out["weight"] = out["weight"].to_numpy(dtype=float) * pop
    return out
